from systeme.FondMarin import yf, load_image, image_resize, load_texture_from_image, unload_image

dim = int(yf*0.045)
mindim = int(yf*0.025)
ico = load_image('jeux/archipel/images/Icones/coeur.png')
image_resize(ico, dim, dim)
coeur = load_texture_from_image(ico)
image_resize(ico, mindim, mindim)
minicoeur = load_texture_from_image(ico)
unload_image(ico)
ico = load_image('jeux/archipel/images/Icones/deplacement.png')
image_resize(ico, dim, dim)
fleche = load_texture_from_image(ico)
unload_image(ico)
ico = load_image('jeux/archipel/images/Icones/marin.png')
image_resize(ico, dim, dim)
marin = load_texture_from_image(ico)
image_resize(ico, mindim, mindim)
minimarin = load_texture_from_image(ico)
unload_image(ico)
ico = load_image('jeux/archipel/images/Icones/organisation.png')
image_resize(ico, dim, dim)
orga = load_texture_from_image(ico)
image_resize(ico, mindim, mindim)
miniorga = load_texture_from_image(ico)
unload_image(ico)
ico = load_image('jeux/archipel/images/Icones/abordage.png')
image_resize(ico, dim, dim)
abordage = load_texture_from_image(ico)
image_resize(ico, mindim, mindim)
miniabordage = load_texture_from_image(ico)
unload_image(ico)
ico = load_image('jeux/archipel/images/Icones/degats.png')
image_resize(ico, dim, dim)
degats = load_texture_from_image(ico)
image_resize(ico, mindim, mindim)
minidegats = load_texture_from_image(ico)
unload_image(ico)